# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainApp.User'),
            preserve_default=False,
        ),
    ]
